language: node_js
before_install: npm install -g npm@'>=2.13.5'
script: npm test
after_success:
- if [ "${TRAVIS_BRANCH}" = "master" ]; then git config --global user.email "${GIT_EMAIL}";
  fi
- if [ "${TRAVIS_BRANCH}" = "master" ]; then git config --global user.name "${GIT_NAME}";
  fi
- if [ "${TRAVIS_BRANCH}" = "master" ]; then  git clone --quiet --branch=stable https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}
  travis-build > /dev/null; fi
- if [ "${TRAVIS_BRANCH}" = "master" ]; then  cd travis-build; fi
- if [ "${TRAVIS_BRANCH}" = "master" ]; then  git fetch --quiet > /dev/null; fi
- if [ "${TRAVIS_BRANCH}" = "master" ]; then  git merge origin/master --no-commit
  > /dev/null; fi
- if [ "${TRAVIS_BRANCH}" = "master" ]; then  git commit -m "Travis CI auto-merge
  from travis build ${TRAVIS_BUILD_NUMBER}"; fi
- if [ "${TRAVIS_BRANCH}" = "master" ]; then  npm version patch -m "Travis CI auto-version
  from travis build ${TRAVIS_BUILD_NUMBER}"; fi
- if [ "${TRAVIS_BRANCH}" = "master" ]; then  git push -fq origin stable > /dev/null;
  fi
before_deploy:
- npm install
deploy:
  skip_cleanup: true
  provider: npm
  email: todd@deepelement.com
  api_key:
    secure: Fl9C9K3t0Jb1Ed6l+mwXSk+iweOmzU2d6/pt0+fn4yW5abKqB2TxUNxcR1G3mlB200yT9Awy6uohppFjWxf7MrY29HsAjnco6gOErqbLNTxNG1bzzuYz0CNGsVBWd7pa/rymkbUHEA8wF9yn0W+LaclaIcsfZslrN/lwsSo3DuHgbJbptCG0mLnqYCIBT3a2/sYRoYMpyzFJEycEG+l9r/pNnfTMG5J9sSCyf48kCqXsgQiTGGaWX6XHEUpH+rDwn0cQRPUM+fa6VJY0DdI/EDd+gCNc4PRczu2lzEZawOlgftAl8+7MAvVGiq316o3/+XMlzOIgjTO+f1I/+KrwGuaIgU4sYaan6abrYUlohJyPCRMAFBtqjtv/fnP1mlUl01XshSvJY2qS8DHpJdfLBGJThII5CACFAIV27ED8oYR6FnHmOjpDRPfwdLYt+1yrk6/kp/fsFV6Dgtvq4SwDDHtKcFBWZQfRQI81W41DvYLyb87NQ12PFwKAe4BRqbBMKcD5ox0DDWoaKsJ2U4aRywdBsCK9fgh7C2vhcMJqi0pPwP9fRbAJxQIzRyb2G5LlvubxQ2vyXO2B/k/WfwXqXq4f4Z0MES91omaxr7/grt8hZrbyAT6/+F2etUvrsX2wUW2L9Vk8oG60eixwwT8CQLA5kcl1qeBwuOZXVHaaoH4=
  on:
    repo: DeepElement/browserify-bridge
    branch: stable
